//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalWebApplication.YelpNearest {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="YelpSearchResult", Namespace="http://schemas.datacontract.org/2004/07/YelpServices")]
    [System.SerializableAttribute()]
    public partial class YelpSearchResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Business[] lstBusinessField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Region objRegionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Business[] lstBusiness {
            get {
                return this.lstBusinessField;
            }
            set {
                if ((object.ReferenceEquals(this.lstBusinessField, value) != true)) {
                    this.lstBusinessField = value;
                    this.RaisePropertyChanged("lstBusiness");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Region objRegion {
            get {
                return this.objRegionField;
            }
            set {
                if ((object.ReferenceEquals(this.objRegionField, value) != true)) {
                    this.objRegionField = value;
                    this.RaisePropertyChanged("objRegion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Region", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Region : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Coordinate centerField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Span spanField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Coordinate center {
            get {
                return this.centerField;
            }
            set {
                if ((object.ReferenceEquals(this.centerField, value) != true)) {
                    this.centerField = value;
                    this.RaisePropertyChanged("center");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Span span {
            get {
                return this.spanField;
            }
            set {
                if ((object.ReferenceEquals(this.spanField, value) != true)) {
                    this.spanField = value;
                    this.RaisePropertyChanged("span");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Business", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Business : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[][] categoriesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Deal[] dealsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string display_phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double distanceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_claimedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_closedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Location locationField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string mobile_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string phoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ratingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rating_img_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rating_img_url_largeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rating_img_url_smallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int review_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Review[] reviewsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string snippet_image_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string snippet_textField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[][] categories {
            get {
                return this.categoriesField;
            }
            set {
                if ((object.ReferenceEquals(this.categoriesField, value) != true)) {
                    this.categoriesField = value;
                    this.RaisePropertyChanged("categories");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Deal[] deals {
            get {
                return this.dealsField;
            }
            set {
                if ((object.ReferenceEquals(this.dealsField, value) != true)) {
                    this.dealsField = value;
                    this.RaisePropertyChanged("deals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display_phone {
            get {
                return this.display_phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.display_phoneField, value) != true)) {
                    this.display_phoneField = value;
                    this.RaisePropertyChanged("display_phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double distance {
            get {
                return this.distanceField;
            }
            set {
                if ((this.distanceField.Equals(value) != true)) {
                    this.distanceField = value;
                    this.RaisePropertyChanged("distance");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_url {
            get {
                return this.image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.image_urlField, value) != true)) {
                    this.image_urlField = value;
                    this.RaisePropertyChanged("image_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_claimed {
            get {
                return this.is_claimedField;
            }
            set {
                if ((this.is_claimedField.Equals(value) != true)) {
                    this.is_claimedField = value;
                    this.RaisePropertyChanged("is_claimed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_closed {
            get {
                return this.is_closedField;
            }
            set {
                if ((this.is_closedField.Equals(value) != true)) {
                    this.is_closedField = value;
                    this.RaisePropertyChanged("is_closed");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Location location {
            get {
                return this.locationField;
            }
            set {
                if ((object.ReferenceEquals(this.locationField, value) != true)) {
                    this.locationField = value;
                    this.RaisePropertyChanged("location");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string mobile_url {
            get {
                return this.mobile_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.mobile_urlField, value) != true)) {
                    this.mobile_urlField = value;
                    this.RaisePropertyChanged("mobile_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone {
            get {
                return this.phoneField;
            }
            set {
                if ((object.ReferenceEquals(this.phoneField, value) != true)) {
                    this.phoneField = value;
                    this.RaisePropertyChanged("phone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rating_img_url {
            get {
                return this.rating_img_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.rating_img_urlField, value) != true)) {
                    this.rating_img_urlField = value;
                    this.RaisePropertyChanged("rating_img_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rating_img_url_large {
            get {
                return this.rating_img_url_largeField;
            }
            set {
                if ((object.ReferenceEquals(this.rating_img_url_largeField, value) != true)) {
                    this.rating_img_url_largeField = value;
                    this.RaisePropertyChanged("rating_img_url_large");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rating_img_url_small {
            get {
                return this.rating_img_url_smallField;
            }
            set {
                if ((object.ReferenceEquals(this.rating_img_url_smallField, value) != true)) {
                    this.rating_img_url_smallField = value;
                    this.RaisePropertyChanged("rating_img_url_small");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int review_count {
            get {
                return this.review_countField;
            }
            set {
                if ((this.review_countField.Equals(value) != true)) {
                    this.review_countField = value;
                    this.RaisePropertyChanged("review_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Review[] reviews {
            get {
                return this.reviewsField;
            }
            set {
                if ((object.ReferenceEquals(this.reviewsField, value) != true)) {
                    this.reviewsField = value;
                    this.RaisePropertyChanged("reviews");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string snippet_image_url {
            get {
                return this.snippet_image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.snippet_image_urlField, value) != true)) {
                    this.snippet_image_urlField = value;
                    this.RaisePropertyChanged("snippet_image_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string snippet_text {
            get {
                return this.snippet_textField;
            }
            set {
                if ((object.ReferenceEquals(this.snippet_textField, value) != true)) {
                    this.snippet_textField = value;
                    this.RaisePropertyChanged("snippet_text");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Location", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Location : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.Coordinate coordinateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string country_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string cross_streetsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] display_addressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double geo_accuracyField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] neighborhoodsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string postal_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string state_codeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string city {
            get {
                return this.cityField;
            }
            set {
                if ((object.ReferenceEquals(this.cityField, value) != true)) {
                    this.cityField = value;
                    this.RaisePropertyChanged("city");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.Coordinate coordinate {
            get {
                return this.coordinateField;
            }
            set {
                if ((object.ReferenceEquals(this.coordinateField, value) != true)) {
                    this.coordinateField = value;
                    this.RaisePropertyChanged("coordinate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string country_code {
            get {
                return this.country_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.country_codeField, value) != true)) {
                    this.country_codeField = value;
                    this.RaisePropertyChanged("country_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string cross_streets {
            get {
                return this.cross_streetsField;
            }
            set {
                if ((object.ReferenceEquals(this.cross_streetsField, value) != true)) {
                    this.cross_streetsField = value;
                    this.RaisePropertyChanged("cross_streets");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] display_address {
            get {
                return this.display_addressField;
            }
            set {
                if ((object.ReferenceEquals(this.display_addressField, value) != true)) {
                    this.display_addressField = value;
                    this.RaisePropertyChanged("display_address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double geo_accuracy {
            get {
                return this.geo_accuracyField;
            }
            set {
                if ((this.geo_accuracyField.Equals(value) != true)) {
                    this.geo_accuracyField = value;
                    this.RaisePropertyChanged("geo_accuracy");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] neighborhoods {
            get {
                return this.neighborhoodsField;
            }
            set {
                if ((object.ReferenceEquals(this.neighborhoodsField, value) != true)) {
                    this.neighborhoodsField = value;
                    this.RaisePropertyChanged("neighborhoods");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string postal_code {
            get {
                return this.postal_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.postal_codeField, value) != true)) {
                    this.postal_codeField = value;
                    this.RaisePropertyChanged("postal_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string state_code {
            get {
                return this.state_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.state_codeField, value) != true)) {
                    this.state_codeField = value;
                    this.RaisePropertyChanged("state_code");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Deal", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Deal : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string additional_restrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string currency_codeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string important_restrictionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.DealOptions[] optionsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double time_endField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double time_startField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string what_you_getField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string additional_restrictions {
            get {
                return this.additional_restrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.additional_restrictionsField, value) != true)) {
                    this.additional_restrictionsField = value;
                    this.RaisePropertyChanged("additional_restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string currency_code {
            get {
                return this.currency_codeField;
            }
            set {
                if ((object.ReferenceEquals(this.currency_codeField, value) != true)) {
                    this.currency_codeField = value;
                    this.RaisePropertyChanged("currency_code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_url {
            get {
                return this.image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.image_urlField, value) != true)) {
                    this.image_urlField = value;
                    this.RaisePropertyChanged("image_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string important_restrictions {
            get {
                return this.important_restrictionsField;
            }
            set {
                if ((object.ReferenceEquals(this.important_restrictionsField, value) != true)) {
                    this.important_restrictionsField = value;
                    this.RaisePropertyChanged("important_restrictions");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.DealOptions[] options {
            get {
                return this.optionsField;
            }
            set {
                if ((object.ReferenceEquals(this.optionsField, value) != true)) {
                    this.optionsField = value;
                    this.RaisePropertyChanged("options");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double time_end {
            get {
                return this.time_endField;
            }
            set {
                if ((this.time_endField.Equals(value) != true)) {
                    this.time_endField = value;
                    this.RaisePropertyChanged("time_end");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double time_start {
            get {
                return this.time_startField;
            }
            set {
                if ((this.time_startField.Equals(value) != true)) {
                    this.time_startField = value;
                    this.RaisePropertyChanged("time_start");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string url {
            get {
                return this.urlField;
            }
            set {
                if ((object.ReferenceEquals(this.urlField, value) != true)) {
                    this.urlField = value;
                    this.RaisePropertyChanged("url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string what_you_get {
            get {
                return this.what_you_getField;
            }
            set {
                if ((object.ReferenceEquals(this.what_you_getField, value) != true)) {
                    this.what_you_getField = value;
                    this.RaisePropertyChanged("what_you_get");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Review", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Review : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string excerptField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double ratingField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rating_img_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rating_img_url_largeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string rating_img_url_smallField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double time_createdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private FinalWebApplication.YelpNearest.User userField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string excerpt {
            get {
                return this.excerptField;
            }
            set {
                if ((object.ReferenceEquals(this.excerptField, value) != true)) {
                    this.excerptField = value;
                    this.RaisePropertyChanged("excerpt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double rating {
            get {
                return this.ratingField;
            }
            set {
                if ((this.ratingField.Equals(value) != true)) {
                    this.ratingField = value;
                    this.RaisePropertyChanged("rating");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rating_img_url {
            get {
                return this.rating_img_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.rating_img_urlField, value) != true)) {
                    this.rating_img_urlField = value;
                    this.RaisePropertyChanged("rating_img_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rating_img_url_large {
            get {
                return this.rating_img_url_largeField;
            }
            set {
                if ((object.ReferenceEquals(this.rating_img_url_largeField, value) != true)) {
                    this.rating_img_url_largeField = value;
                    this.RaisePropertyChanged("rating_img_url_large");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string rating_img_url_small {
            get {
                return this.rating_img_url_smallField;
            }
            set {
                if ((object.ReferenceEquals(this.rating_img_url_smallField, value) != true)) {
                    this.rating_img_url_smallField = value;
                    this.RaisePropertyChanged("rating_img_url_small");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double time_created {
            get {
                return this.time_createdField;
            }
            set {
                if ((this.time_createdField.Equals(value) != true)) {
                    this.time_createdField = value;
                    this.RaisePropertyChanged("time_created");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public FinalWebApplication.YelpNearest.User user {
            get {
                return this.userField;
            }
            set {
                if ((object.ReferenceEquals(this.userField, value) != true)) {
                    this.userField = value;
                    this.RaisePropertyChanged("user");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="DealOptions", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class DealOptions : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formatted_original_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string formatted_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool is_quantity_limitedField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double original_priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double priceField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string purchase_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double remaining_countField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string titleField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formatted_original_price {
            get {
                return this.formatted_original_priceField;
            }
            set {
                if ((object.ReferenceEquals(this.formatted_original_priceField, value) != true)) {
                    this.formatted_original_priceField = value;
                    this.RaisePropertyChanged("formatted_original_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string formatted_price {
            get {
                return this.formatted_priceField;
            }
            set {
                if ((object.ReferenceEquals(this.formatted_priceField, value) != true)) {
                    this.formatted_priceField = value;
                    this.RaisePropertyChanged("formatted_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool is_quantity_limited {
            get {
                return this.is_quantity_limitedField;
            }
            set {
                if ((this.is_quantity_limitedField.Equals(value) != true)) {
                    this.is_quantity_limitedField = value;
                    this.RaisePropertyChanged("is_quantity_limited");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double original_price {
            get {
                return this.original_priceField;
            }
            set {
                if ((this.original_priceField.Equals(value) != true)) {
                    this.original_priceField = value;
                    this.RaisePropertyChanged("original_price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double price {
            get {
                return this.priceField;
            }
            set {
                if ((this.priceField.Equals(value) != true)) {
                    this.priceField = value;
                    this.RaisePropertyChanged("price");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string purchase_url {
            get {
                return this.purchase_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.purchase_urlField, value) != true)) {
                    this.purchase_urlField = value;
                    this.RaisePropertyChanged("purchase_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double remaining_count {
            get {
                return this.remaining_countField;
            }
            set {
                if ((this.remaining_countField.Equals(value) != true)) {
                    this.remaining_countField = value;
                    this.RaisePropertyChanged("remaining_count");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string title {
            get {
                return this.titleField;
            }
            set {
                if ((object.ReferenceEquals(this.titleField, value) != true)) {
                    this.titleField = value;
                    this.RaisePropertyChanged("title");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Coordinate", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Coordinate : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitudeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitudeField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude {
            get {
                return this.latitudeField;
            }
            set {
                if ((this.latitudeField.Equals(value) != true)) {
                    this.latitudeField = value;
                    this.RaisePropertyChanged("latitude");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude {
            get {
                return this.longitudeField;
            }
            set {
                if ((this.longitudeField.Equals(value) != true)) {
                    this.longitudeField = value;
                    this.RaisePropertyChanged("longitude");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="User", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class User : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string idField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string image_urlField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string id {
            get {
                return this.idField;
            }
            set {
                if ((object.ReferenceEquals(this.idField, value) != true)) {
                    this.idField = value;
                    this.RaisePropertyChanged("id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_url {
            get {
                return this.image_urlField;
            }
            set {
                if ((object.ReferenceEquals(this.image_urlField, value) != true)) {
                    this.image_urlField = value;
                    this.RaisePropertyChanged("image_url");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string name {
            get {
                return this.nameField;
            }
            set {
                if ((object.ReferenceEquals(this.nameField, value) != true)) {
                    this.nameField = value;
                    this.RaisePropertyChanged("name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Span", Namespace="http://schemas.datacontract.org/2004/07/YelpSharp.Data")]
    [System.SerializableAttribute()]
    public partial class Span : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double latitude_deltaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private double longitude_deltaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double latitude_delta {
            get {
                return this.latitude_deltaField;
            }
            set {
                if ((this.latitude_deltaField.Equals(value) != true)) {
                    this.latitude_deltaField = value;
                    this.RaisePropertyChanged("latitude_delta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public double longitude_delta {
            get {
                return this.longitude_deltaField;
            }
            set {
                if ((this.longitude_deltaField.Equals(value) != true)) {
                    this.longitude_deltaField = value;
                    this.RaisePropertyChanged("longitude_delta");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="YelpNearest.YelpIService")]
    public interface YelpIService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YelpIService/searchResults", ReplyAction="http://tempuri.org/YelpIService/searchResultsResponse")]
        FinalWebApplication.YelpNearest.YelpSearchResult searchResults(string searchTerm, string location);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/YelpIService/searchResults", ReplyAction="http://tempuri.org/YelpIService/searchResultsResponse")]
        System.Threading.Tasks.Task<FinalWebApplication.YelpNearest.YelpSearchResult> searchResultsAsync(string searchTerm, string location);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface YelpIServiceChannel : FinalWebApplication.YelpNearest.YelpIService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class YelpIServiceClient : System.ServiceModel.ClientBase<FinalWebApplication.YelpNearest.YelpIService>, FinalWebApplication.YelpNearest.YelpIService {
        
        public YelpIServiceClient() {
        }
        
        public YelpIServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public YelpIServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YelpIServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public YelpIServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public FinalWebApplication.YelpNearest.YelpSearchResult searchResults(string searchTerm, string location) {
            return base.Channel.searchResults(searchTerm, location);
        }
        
        public System.Threading.Tasks.Task<FinalWebApplication.YelpNearest.YelpSearchResult> searchResultsAsync(string searchTerm, string location) {
            return base.Channel.searchResultsAsync(searchTerm, location);
        }
    }
}
